name: restobuy_supplier_flutter
description: Restobuy Supplier Flutter App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
versionCode: 1
versionName: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter_sdk: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  equatable: ^2.0.0
  http: ^0.13.1
  dartz: ^0.10.0-nullsafety.1
  get_it: ^6.1.1
  google_fonts: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.0.0
  wiredash: ^0.6.2
  hive: ^2.0.4
  path_provider: ^2.0.1
  youtube_player_flutter: ^8.0.0
  flare_flutter: ^3.0.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  test: ^1.16.5
  bloc_test: ^8.0.0
  mockito: ^5.0.5
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/gifs/
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/

